### ISSUE TITLE
How can I make send button always visible?

### ISSUE THREAD

**Issue by rmControls** [flyerhq/flutter_chat_ui#62] opened 2021-07-17 03:35 UTC
1) How can I make send button always visible?
2) How to give background color and border radius for input text field like below? (Text field decoration)
![image](https://user-images.githubusercontent.com/27656141/126024365-9378fdf3-9135-46df-bccf-64483158cdc3.png)

**Comment by demchenkoalex** [comment] 2021-07-17 05:31
Hi, both are not available by design. PRs are open though :)

**Comment by demchenkoalex** [comment] 2021-08-29 11:42
Closed by #76

**Comment by rmControls** [comment] 2021-08-29 16:59
I believe the second point is still open.... (Input TextField Decoration)..

**Comment by demchenkoalex** [comment] 2021-08-29 17:16
Yeah, sorry

**Comment by demchenkoalex** [comment] 2021-09-01 08:36
Released in [v1.3.2](https://github.com/flyerhq/flutter_chat_ui/releases/tag/v1.3.2).

**Closed by demchenkoalex** 2021-09-01 08:36 UTC
Labels: feature
