### ISSUE TITLE
Weird top padding

### ISSUE THREAD

**Issue by rigroch** [flyerhq/flutter_chat_ui#321] opened 2022-09-16 01:14 UTC
Hello, I faced this issue.
Message bubble contains incomprehensible padding at the top.
What's wrong with me...? Can you help me?

More info..
flutter: 3.0.5
flutter_chat_ui: ^1.6.4
flutter_chat_types: ^3.4.5

iOS(14.x):
<img width="200" src="https://user-images.githubusercontent.com/939633/190534561-f2c4c8c0-7cdb-431c-bd74-ac607c0308fe.PNG">

Web(Chrome):
<img width="509" alt="스크린샷 2022-09-16 오전 9 49 20" src="https://user-images.githubusercontent.com/939633/190534581-28c88f2a-b581-498a-99e4-4e8a0b10d716.png">

macOS:
<img width="316" alt="스크린샷 2022-09-16 오전 9 52 43" src="https://user-images.githubusercontent.com/939633/190534584-d4c2e955-b2d5-488d-8f5e-fb61dd413179.png">

**Comment by rigroch** [comment] 2022-09-16 01:32
I set isTextMessageTextSelectable: false,
It's disappeared.

I think bug of following option.

**Comment by jld3103** [comment] 2022-09-16 03:39
I think it's a duplicate of https://github.com/flyerhq/flutter_chat_ui/issues/315

**Comment by jld3103** [comment] 2022-09-16 03:40
You need to wrap the app in a `MaterialApp` or `CupertinoApp`.

**Comment by rigroch** [comment] 2022-09-16 05:32
> You need to wrap the app in a `MaterialApp` or `CupertinoApp`.

I'd already use MaterialApp...
<img width="180" alt="스크린샷 2022-09-16 오후 2 32 26" src="https://user-images.githubusercontent.com/939633/190563731-cb1904c7-0acf-4191-a7d8-f7366479e072.png">

**Comment by demchenkoalex** [comment] 2022-10-02 22:05
Will take a look!

**Comment by demchenkoalex** [comment] 2022-10-29 15:43
Yes, as suggested here, `Scaffold` is required, I am not sure what happens with Flutter if you don't provide it, everything is underlined with yellow and generally layout breaks.

**Closed by demchenkoalex** 2022-10-29 15:43 UTC
Labels: bug
