### ISSUE TITLE
video from url

### ISSUE THREAD

**Issue by pranavkumarbg** [flyerhq/flutter_chat_ui#535] opened 2023-12-07 11:13 UTC
## Is your feature request related to a problem?
A clear and concise description of what the problem is or why we should process it.

## What solution would you suggest?
A clear and concise description of what you want to happen. How would it solve the problem of yours?

## Extras
**Screenshots or videos 📸**
If applicable, add screenshots or videos to help explain your feature.

**Code snippets 📝**
If applicable, add code samples to help explain your feature.

```dart
// Your snippet here...
```

## Related issues/PRs
Let us know if this is related to any issue/pull request.

**Comment by marcobraghim** [comment] 2023-12-21 12:12
I would like to know how this package deal with videos since I'm not able to see it working... The type exists (types.VideoMessage) but it renders nothing on the screen...

**Comment by demchenkoalex** [comment] 2023-12-25 14:58
it doesn't. Types were added for people to build their own video messages, because they were not added in `v1`. Will be part of `v2`.

**Closed** 2023-12-25 14:58 UTC
Labels: feature

**Comment by Parfyonator** [comment] 2024-01-27 20:24
Hi @demchenkoalex. I guess it is a good idea to mention it somewhere in README and give a link to some example (if possible). It is really frustrating to debug code for hours only to realize that it is not your mistake but an intended behaviour.
